# 1

Sometimes there is a need to create an empty and full array simultaneously for a particular question.

Create a 3x4 empty numpy array
Create a 3x4 full numpy array where every element is equal to 55.



answar:

In [3]:
import numpy as np
#creating empty array
empty_array = np.empty([3,4], dtype=int)
print("empty array :\n", empty_array, end="\n")

#creating full array
full_55_array = np.full([3,4],66, dtype=int) 
print("full 55 array:\n", full_55_array, end="\n")

empty array :
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
full 55 array:
 [[66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]]


# 2

Find the average of non-zero elements of a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8]) .

answar:

In [16]:
a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])
a[a != 0].mean()

4.625

# 3