# 1

Sometimes there is a need to create an empty and full array simultaneously for a particular question.

Create a 3x4 empty numpy array
Create a 3x4 full numpy array where every element is equal to 55.



answar:

In [3]:
import numpy as np
#creating empty array
empty_array = np.empty([3,4], dtype=int)
print("empty array :\n", empty_array, end="\n")

#creating full array
full_55_array = np.full([3,4],66, dtype=int) 
print("full 55 array:\n", full_55_array, end="\n")

empty array :
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
full 55 array:
 [[66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]]


# 2

Find the average of non-zero elements of a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8]) .

answar:

In [49]:
import numpy as np
a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])
a[a != 0].mean()

4.625

# 3

Numpy Array Middle Rows
a_3d = np.array(
    [[[10, 25, 70], [30, 45, 55], [20, 45, 7]],
    [[50, 65, 8], [70, 85, 10], [11, 22, 33]]]
)

answare:

In [50]:
import numpy as np
a_3d = np.array( [[[10, 25, 70], [30, 45, 55], [20, 45, 7]], [[50, 65, 8], [70, 85, 10], [11, 22, 33]]] )

# Access the Middle rows of 3-D array

a_3d

res = a_3d[:,[1]]
print(res)

[[[30 45 55]]

 [[70 85 10]]]


# 4

Create a list in Python and store it in the python_list1 variable. Then create a one-dimensional ndarray using the python_list1 variable and store it in the ndarray_1d variable.

answar:

In [61]:
import numpy as np
python_list1 = [*range(10)]
one_dimensional_array = np.array(python_list1, dtype=int)
one_dimensional_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5

Create a nested list in Python and store it in the python_list2 variable. Then create a two-dimensional ndarray using the python_list2 variable and store it in the ndarray_2d variable.

answar:

In [65]:
import numpy as np
python_list2 = [[*range(10)], [*range(10,20)]]
two_dimensional_array = np.array(python_list2)
two_dimensional_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# 6

Create a 2-dimensional array of size 3x3 named x, composed of 1-byte integer elements.


answar:

In [80]:
import numpy as np
my_array = np.random.randint(0,10,(3,3), dtype="i8")

In [81]:
my_array

array([[9, 9, 9],
       [5, 3, 1],
       [4, 5, 5]])