# 1

Sometimes there is a need to create an empty and full array simultaneously for a particular question.

Create a 3x4 empty numpy array
Create a 3x4 full numpy array where every element is equal to 55.



answer:

In [3]:
import numpy as np
#creating empty array
empty_array = np.empty([3,4], dtype=int)
print("empty array :\n", empty_array, end="\n")

#creating full array
full_55_array = np.full([3,4],66, dtype=int) 
print("full 55 array:\n", full_55_array, end="\n")

empty array :
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
full 55 array:
 [[66 66 66 66]
 [66 66 66 66]
 [66 66 66 66]]


# 2

Find the average of non-zero elements of a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8]) .

answer:

In [49]:
import numpy as np
a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])
a[a != 0].mean()

4.625

# 3

Numpy Array Middle Rows
a_3d = np.array(
    [[[10, 25, 70], [30, 45, 55], [20, 45, 7]],
    [[50, 65, 8], [70, 85, 10], [11, 22, 33]]]
)

answer:

In [50]:
import numpy as np
a_3d = np.array( [[[10, 25, 70], [30, 45, 55], [20, 45, 7]], [[50, 65, 8], [70, 85, 10], [11, 22, 33]]] )

# Access the Middle rows of 3-D array

a_3d

res = a_3d[:,[1]]
print(res)

[[[30 45 55]]

 [[70 85 10]]]


# 4

Create a list in Python and store it in the python_list1 variable. Then create a one-dimensional ndarray using the python_list1 variable and store it in the ndarray_1d variable.

answer:

In [61]:
import numpy as np
python_list1 = [*range(10)]
one_dimensional_array = np.array(python_list1, dtype=int)
one_dimensional_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5

Create a nested list in Python and store it in the python_list2 variable. Then create a two-dimensional ndarray using the python_list2 variable and store it in the ndarray_2d variable.

answer:

In [65]:
import numpy as np
python_list2 = [[*range(10)], [*range(10,20)]]
two_dimensional_array = np.array(python_list2)
two_dimensional_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# 6

Create a 2-dimensional array of size 3x3 named x, composed of 1-byte integer elements.


answer:

In [87]:
import numpy as np
my_array = np.random.randint(0,10,(3,3), dtype="i1")

In [88]:
my_array

array([[4, 9, 2],
       [3, 4, 3],
       [7, 1, 7]], dtype=int8)

# 7

Create an array containing the numbers 0 to 999 and store it in variable a1 .

answer:

In [102]:
a1 = np.arange(0,1000)

# 8

Create an array of dtype float containing the numbers -3 to 3 and store it in variable a2 .

(The number 3 itself is not in the array)

answer:

In [107]:
a2 = np.arange(-2, 3, dtype="f4")

In [108]:
a2

array([-2., -1.,  0.,  1.,  2.], dtype=float32)

# 9

Create an array that starts at 2 and goes up to 10 in steps of 0.1 and store it in variable a3

(The number 10 itself is not in the array)

answer:

In [128]:
a3 = np.arange(2,10,0.1)

In [110]:
a3

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
       5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
       7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
       8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7,
       9.8, 9.9])

# 10

Create an array that starts at -0.5 and goes up to 0.2 in steps of 0.1 and store it in variable a4.

(The number 0.2 itself is not in the array)

answer:

In [124]:
a4 = np.linspace(-0.5, 0.2,7)

In [125]:
a4

array([-0.5       , -0.38333333, -0.26666667, -0.15      , -0.03333333,
        0.08333333,  0.2       ])

# 11

Create an array containing 7 elements between the numbers 1 to 121 in such a way that the numbers 1 and 121 are part of this array and the distance between the numbers should be equal. store the array in a5 variable

answer:

In [126]:
a5 = np.linspace(1, 121, 7)

In [127]:
a5

array([  1.,  21.,  41.,  61.,  81., 101., 121.])

# 12

Create an array containing 16 elements between the numbers -3 to 3 in such a way that the numbers -3 and 3 are part of this array and the distance between the numbers should be equal. store the array in a6 variable

answer:

In [134]:
a6 = np.linspace(-3, 3, 16)

In [135]:
a6

array([-3. , -2.6, -2.2, -1.8, -1.4, -1. , -0.6, -0.2,  0.2,  0.6,  1. ,
        1.4,  1.8,  2.2,  2.6,  3. ])

# 13

Create an 4×4 array that its main diameter is equal to 1 and other elements are equal to zero 

and store this variable in a7 variable

answer:

In [154]:
a7 = np.eye(4)

In [155]:
a7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 14

Create a 7×7 array that it's main diameter contains the numbers from 1 to 121 with equal distance and other elements are equal to zero then store it in the a9 variable.

answer:

In [170]:
a9 = np.diag(np.linspace(1,121,7))


In [171]:
a9

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  21.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  41.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  61.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  81.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 101.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0., 121.]])

# 15

A 5×5 array is stored in a variable named z, store the value of the second diameter lower than the main diameter in a variable called a10

answer:

In [198]:
z = np.eye(5, k=-2)
a10 = np.diag(z, -2)
print(z)
a10

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


array([1., 1., 1.])

# 16

Create a 6x4 array with all zero elements and store it in variable a11


answer:

In [177]:
a11 = np.zeros([6,4])

In [178]:
a11

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 17

Create a 6x4 array with all one elements and store it in variable a12

answer:

In [179]:
a12 = np.ones([6,4])

In [180]:
a12

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 18

Create a 6x4 array with all random elements and store it in variable a13 .

answer:

In [209]:
np.random.default_rng(seed=32).random((6, 4))

array([[0.16024283, 0.5722295 , 0.37713555, 0.32293518],
       [0.68661389, 0.97223203, 0.96683025, 0.67129842],
       [0.83010157, 0.45971184, 0.31707756, 0.54255623],
       [0.60122338, 0.91302719, 0.40845736, 0.55091596],
       [0.4104853 , 0.15238988, 0.04054205, 0.23318279],
       [0.60778421, 0.90482775, 0.00868426, 0.45920704]])

# 19


Create a 8x3 array with all its elements equal to the "Pytopia"  and then store it in the a15  variable.

answer:

In [223]:
a15 = np.full((8,3), "Pytopia")

In [224]:
a15

array([['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia'],
       ['Pytopia', 'Pytopia', 'Pytopia']], dtype='<U7')

# 20

Using numpy with one line of code, create an array similar to the one below and store it in the a16  variable.

answer:

In [233]:
a16 = np.full((6,3), [-np.inf,np.nan,np.inf])

In [234]:
a16

array([[-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf]])